#!/command/with-contenv sh

php /var/www/artisan queue:work \
    --max-jobs $WORKER_MAX_JOBS \
    --sleep $WORKER_SLEEP \
    --rest $WORKER_REST \
    --timeout = 0 \
    --tries $WORKER_TRIES \
    --force
